# Generated by Django 2.0.2 on 2018-03-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('first', '0003_org_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='academic_rank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(default='add', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='orc_id',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='position',
            field=models.CharField(default='org', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='researcher_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='science_degree',
            field=models.CharField(default='org', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='scientific_interest',
            field=models.CharField(default='org', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.CharField(default='sex', max_length=200),
            preserve_default=False,
        ),
    ]
