# Generated by Django 2.0.2 on 2018-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('first', '0004_auto_20180318_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='placeOfWork',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
