# Generated by Django 2.0.2 on 2018-03-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20180327_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='lon',
            new_name='lng',
        ),
    ]
