# Generated by Django 2.0.2 on 2018-03-27 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='Org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Org'),
        ),
    ]
