# Generated by Django 2.0.2 on 2018-03-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_auto_20180327_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
