# Generated by Django 2.0.2 on 2018-03-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_auto_20180328_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='check_anycity',
            field=models.BooleanField(default=False),
        ),
    ]
