# Generated by Django 2.0.2 on 2018-03-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_app_check_anycity'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_planed',
            field=models.BooleanField(default=True),
        ),
    ]
