# Generated by Django 2.0.2 on 2018-03-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_app_is_planed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='is_planed',
        ),
        migrations.AddField(
            model_name='app',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
