# Generated by Django 2.0.2 on 2018-03-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_auto_20180328_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
