# Generated by Django 2.0.2 on 2018-03-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_auto_20180330_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cms',
            options={'verbose_name_plural': 'CMS'},
        ),
        migrations.AddField(
            model_name='account',
            name='marker',
            field=models.URLField(default='https://psv4.userapi.com/c834502/u187881541/docs/d5/7cdea22a5d38/lect.png?extra=3ik8bvlrIhSUjQe0kw8JkVTdyTrVsBdOtgHqtdRjkPb4WlNqcd7OLfQRJcuK2pUhXjxY7Rjx65NhtX4EJDfd389sEG3ZhpnrJoNZ8LKT7a-6_nfBKlFm_lFVXQ3bAYJFMHtNFfirA0OC5tRD'),
        ),
    ]
