# Generated by Django 2.0.2 on 2018-04-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_auto_20180330_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Lecture', 'verbose_name_plural': 'Lectures'},
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'verbose_name': 'Org', 'verbose_name_plural': 'Orgs'},
        ),
        migrations.AlterField(
            model_name='account',
            name='marker',
            field=models.URLField(default='https://psv4.userapi.com/c834502/u187881541/docs/d5/7cdea22a5d38/lect.png?extra=3ik8bvlrIhSUjQe0kw8JkVTdyTrVsBdOtgHqtdRjkPb4WlNqcd7OLfQRJcuK2pUhXjxY7Rjx65NhtX4EJDfd389sEG3ZhpnrJoNZ8LKT7a-6_nfBKlFm_lFVXQ3bAYJFMHtNFfirA0OC5tRD', max_length=500),
        ),
        migrations.AddField(
            model_name='form',
            name='inputs',
            field=models.ManyToManyField(to='first.Input'),
        ),
    ]
