# Generated by Django 2.0.5 on 2018-09-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapcheck',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='mapcheck',
            name='coord_lat',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mapcheck',
            name='coord_long',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
