# Generated by Django 2.1.1 on 2018-09-20 20:21

from django.db import migrations, models
import second.models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_auto_20180919_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('flag', models.ImageField(upload_to='', verbose_name=second.models.flag_upload_to)),
            ],
        ),
    ]
