# Generated by Django 2.1.1 on 2018-09-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0007_organization_contact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cntr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='c0untry',
            name='orgs',
            field=models.ManyToManyField(blank=True, null=True, to='second.Organization'),
        ),
    ]
