# Generated by Django 2.1.1 on 2018-10-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0008_auto_20180922_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cntr',
        ),
        migrations.AlterModelOptions(
            name='flags',
            options={'verbose_name_plural': 'Flags'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='hided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='c0untry',
            name='orgs',
            field=models.ManyToManyField(blank=True, to='second.Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_confirm',
            field=models.BooleanField(default=False, verbose_name='accepted'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='organization name'),
        ),
    ]
