# Generated by Django 2.1.1 on 2018-10-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0009_auto_20181006_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
